baseurl = "http://kamichidu.github.com/"
title = "なるはやで いい感じの 動作確認"
languageCode = "ja-jp"
theme = "twentyfourteen"

[taxonomies]
    categories = "categories"
    tags = "tags"

[params]
    author = "kamichidu <c.kamunagi (at) gmail.com>"
