baseurl = "//kamichidu.github.com/"
title = "なるはやで いい感じの 動作確認"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "twentyfourteen"
googleAnalytics = "UA-71082560-1"
disqusShortname = "naruhaya"

[taxonomies]
    categories = "categories"
    tags = "tags"
    archives = "archives"

[params]
    author = "kamichidu"
    authorEmail = "c.kamunagi (at) gmail.com"
    authorGithub = "kamichidu"
    authorTwitter = "kamichidu"
    numOfRecents = 5
